device: cuda
layer_size: 600
n_layers: 8
learning_rate: 0.000001
replay_size: 500000
eps_init: 0.9
eps_final: 0.05
eps_decay_steps: 1000000
use_random_walk: True
batch_size: 32
discount: 0.993
tau: 0.003